# Generated by Django 4.1.5 on 2023-03-26 06:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/countries')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_number', models.IntegerField()),
                ('factor_date', models.DateField()),
                ('total_interest', models.IntegerField()),
                ('deliver_by', models.CharField(max_length=100)),
                ('recived_by', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/kinds')),
            ],
        ),
        migrations.CreateModel(
            name='Medician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(blank=True, max_length=100, null=True)),
                ('no_pocket', models.IntegerField(blank=True, null=True)),
                ('ml', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField()),
                ('existence', models.IntegerField(default=0)),
                ('minmum_existence', models.FloatField()),
                ('maximum_existence', models.FloatField()),
                ('dividing_rules', models.TextField(blank=True, null=True)),
                ('cautions', models.TextField(blank=True, null=True)),
                ('usages', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/medician')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.kind')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PharmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=50)),
                ('ceo_phone', models.IntegerField(blank=True, null=True)),
                ('manager', models.CharField(max_length=50)),
                ('manager_phone', models.IntegerField(blank=True, null=True)),
                ('visitor', models.CharField(max_length=50)),
                ('visitor_phone', models.IntegerField(blank=True, null=True)),
                ('companies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('company_phone_1', models.IntegerField()),
                ('company_phone_2', models.IntegerField(blank=True, null=True)),
                ('company_online', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/pharm_groub')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('rsponsible', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/stores')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.IntegerField()),
                ('prescription_number', models.CharField(max_length=60)),
                ('medician', models.ManyToManyField(to='core.medician')),
            ],
        ),
        migrations.AddField(
            model_name='medician',
            name='pharm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pharmgroup'),
        ),
        migrations.AddField(
            model_name='medician',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.unit'),
        ),
        migrations.CreateModel(
            name='EntranceThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_in_factor', models.IntegerField()),
                ('each_price', models.FloatField(default=0)),
                ('discount_money', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('total_purchase', models.FloatField()),
                ('bonus', models.IntegerField(default=0)),
                ('quantity_bonus', models.IntegerField(default=0)),
                ('register_quantity', models.IntegerField()),
                ('each_purchase_price', models.FloatField(null=True)),
                ('interest_money', models.FloatField()),
                ('interest_percent', models.FloatField()),
                ('each_sell_price', models.FloatField()),
                ('total_sell', models.FloatField()),
                ('interest', models.FloatField()),
                ('expire_date', models.DateField()),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entrance')),
                ('medician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medician')),
            ],
        ),
        migrations.AddField(
            model_name='entrance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pharmcompany'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='final_register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.finalregister'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='medicians',
            field=models.ManyToManyField(through='core.EntranceThrough', to='core.medician'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentmethod'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
    ]
