# Generated by Django 4.1.5 on 2023-03-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancethrough',
            name='each_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='entrancethrough',
            name='total_purchase',
            field=models.FloatField(default=1),
        ),
    ]
