# Generated by Django 4.1.5 on 2023-03-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionthrough',
            name='each_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionthrough',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prescriptionthrough',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
