# Generated by Django 4.1.5 on 2023-03-24 16:28

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('code', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PharmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=50)),
                ('ceo_phone', models.IntegerField(blank=True, null=True)),
                ('manager', models.CharField(max_length=50)),
                ('manager_phone', models.IntegerField(blank=True, null=True)),
                ('visitor', models.CharField(max_length=50)),
                ('visitor_phone', models.IntegerField(blank=True, null=True)),
                ('companies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('company_phone_1', models.IntegerField()),
                ('company_phone_2', models.IntegerField(blank=True, null=True)),
                ('company_online', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PharmGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/pharm_groub')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=200)),
                ('rsponsible', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/stores')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/countries'),
        ),
        migrations.AddField(
            model_name='kind',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/kinds'),
        ),
        migrations.AddField(
            model_name='medician',
            name='existence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medician',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/medician'),
        ),
        migrations.CreateModel(
            name='EntranceThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('each_price', models.FloatField(null=True)),
                ('total', models.FloatField(null=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('entrance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entrance')),
                ('medician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medician')),
            ],
        ),
        migrations.AddField(
            model_name='entrance',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pharmcompany'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='medicians',
            field=models.ManyToManyField(through='core.EntranceThroughModel', to='core.medician'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
        migrations.AlterField(
            model_name='medician',
            name='pharm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pharmgroup'),
        ),
        migrations.DeleteModel(
            name='Pharm_Group',
        ),
    ]
