# Generated by Django 4.1.5 on 2023-03-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancethrough',
            name='each_price_factor',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='medician',
            name='existence',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.personalname'),
        ),
    ]
