# Generated by Django 4.1.5 on 2023-03-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='existence',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
