# Generated by Django 4.1.5 on 2023-06-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='factor_date',
            field=models.DateTimeField(),
        ),
    ]
