# Generated by Django 4.1.5 on 2023-03-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kind',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/kinds'),
        ),
    ]
