# Generated by Django 4.1.5 on 2023-06-08 10:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='factor_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
