# Generated by Django 4.1.5 on 2023-05-02 06:36

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='rsponsible',
            new_name='responsible',
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/countries'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/kinds'),
        ),
        migrations.AlterField(
            model_name='medician',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/medician'),
        ),
        migrations.AlterField(
            model_name='pharmgroup',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/pharm_groub'),
        ),
    ]
