# Generated by Django 4.1.5 on 2023-07-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancethrough',
            name='lease',
            field=models.BooleanField(default=False),
        ),
    ]
