# Generated by Django 4.1.5 on 2023-07-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='last_purchased',
            field=models.FloatField(default=0),
        ),
    ]
