# Generated by Django 4.1.5 on 2023-03-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kind_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/countries'),
        ),
        migrations.AddField(
            model_name='pharm_group',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/pharm_groub'),
        ),
    ]
