# Generated by Django 4.1.5 on 2023-07-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medician_last_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='core.department'),
        ),
    ]
