# Generated by Django 4.1.5 on 2023-03-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entrancethrough_each_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrancethrough',
            old_name='each_price',
            new_name='each_price_factor',
        ),
        migrations.AlterField(
            model_name='entrancethrough',
            name='register_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
