# Generated by Django 4.1.5 on 2023-05-24 06:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctorname_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmcompany',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='pharmcompany',
            name='ceo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmcompany',
            name='companies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='pharmcompany',
            name='company_phone_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmcompany',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pharmcompany',
            name='manager',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pharmcompany',
            name='visitor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
