# Generated by Django 4.1.5 on 2023-05-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_prescription_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
