# Generated by Django 4.1.5 on 2023-06-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entrance_factor_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='round_number',
        ),
    ]
