# Generated by Django 4.1.5 on 2023-07-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entrancethrough_lease'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='discount_percent',
            field=models.FloatField(default=0),
        ),
    ]
