# Generated by Django 4.1.5 on 2023-06-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medician_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='wholesale',
            field=models.CharField(choices=[('WHOLESALE', 'WHOLESAVE'), ('SINGULAR', 'SINGULAR')], default=1, max_length=100),
        ),
    ]
