# Generated by Django 4.1.5 on 2023-03-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_currency_entrance_pharmcompany_pharmgroup_store_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrancethroughmodel',
            name='currency',
        ),
    ]
