# Generated by Django 4.1.5 on 2023-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_entrancethrough_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancethrough',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescriptionthrough',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
