# Generated by Django 4.1.5 on 2023-06-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_prescription_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='celling_start',
            field=models.FloatField(default=0),
        ),
    ]
