# Generated by Django 4.1.5 on 2023-03-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_entrancethroughmodel_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='medicians',
            field=models.ManyToManyField(to='core.medician'),
        ),
    ]
