# Generated by Django 4.1.5 on 2023-03-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_each_price_entrancethrough_each_price_factor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrancethrough',
            name='interest',
        ),
        migrations.AddField(
            model_name='entrancethrough',
            name='bonus_interest',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='entrancethrough',
            name='total_interest',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entrancethrough',
            name='each_purchase_price',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='entrancethrough',
            name='each_sell_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entrancethrough',
            name='interest_percent',
            field=models.FloatField(default=20),
        ),
        migrations.AlterField(
            model_name='entrancethrough',
            name='total_sell',
            field=models.FloatField(default=0),
        ),
    ]
