# Generated by Django 4.1.5 on 2023-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_country_image_pharm_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/medician'),
        ),
    ]
