# Generated by Django 4.1.5 on 2023-05-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pharmcompany_address_alter_pharmcompany_ceo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
