# Generated by Django 4.1.5 on 2023-07-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_entrance_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
