# Generated by Django 4.1.5 on 2023-05-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entrancethrough_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outrancethrough',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2023-05-30T12:10:48.355980+04:30'),
            preserve_default=False,
        ),
    ]
