# Generated by Django 4.1.5 on 2023-03-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_prescription_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_number',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
