# Generated by Django 4.1.5 on 2023-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_entrance_factor_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='deliver_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='recived_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
