# Generated by Django 4.1.5 on 2023-07-22 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_currency_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revenuetrough',
            unique_together={('revenue', 'prescription')},
        ),
        migrations.CreateModel(
            name='MedicineWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('includes', models.ManyToManyField(related_name='medicines', to='core.medician')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medician')),
            ],
        ),
    ]
