# Generated by Django 4.1.5 on 2023-03-17 08:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_medician_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ceo', models.CharField(max_length=50)),
                ('ceo_phone', models.IntegerField(blank=True, null=True)),
                ('manager', models.CharField(max_length=50)),
                ('manager_phone', models.IntegerField(blank=True, null=True)),
                ('visitor', models.CharField(max_length=50)),
                ('visitor_phone', models.IntegerField(blank=True, null=True)),
                ('companies', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('company_phone_1', models.IntegerField()),
                ('company_phone_2', models.IntegerField(blank=True, null=True)),
                ('company_online', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
    ]
