# Generated by Django 4.1.5 on 2023-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_department_celling_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='rounded_number',
            field=models.FloatField(default=0),
        ),
    ]
