# Generated by Django 4.1.5 on 2023-05-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_store_address_alter_store_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='deliver_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='factor_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='recived_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
