# Generated by Django 4.1.5 on 2023-06-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_entrance_wholesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='factor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
