# Generated by Django 4.1.5 on 2023-03-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_entrance_medicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancethroughmodel',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currency'),
        ),
        migrations.AlterField(
            model_name='entrance',
            name='medicians',
            field=models.ManyToManyField(through='core.EntranceThroughModel', to='core.medician'),
        ),
    ]
