# Generated by Django 4.1.5 on 2023-03-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_entrancethrough_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancethrough',
            name='each_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='entrancethrough',
            name='interest_money',
            field=models.FloatField(default=0),
        ),
    ]
