# Generated by Django 4.1.5 on 2023-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city_user_country_user_currency_user_department_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='khairat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='rounded',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='revenue',
            name='start_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='zakat',
            field=models.FloatField(default=0),
        ),
    ]
