# Generated by Django 4.1.5 on 2023-05-24 11:06

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_entrance_deliver_by_alter_entrance_factor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='factor_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
