# Generated by Django 4.1.5 on 2023-07-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_revenue_khairat_revenue_rounded_revenue_start_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='revenue_through',
            field=models.ManyToManyField(through='core.RevenueTrough', to='core.prescription'),
        ),
    ]
