# Generated by Django 4.1.5 on 2023-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_entrance_factor_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrance',
            name='wholesale',
            field=models.CharField(choices=[(1, 'WHOLESALE'), (2, 'SINGULAR')], default=1, max_length=100),
        ),
    ]
