# Generated by Django 4.1.5 on 2023-03-17 08:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pharmcompany'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmcompany',
            name='companies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
    ]
