# Generated by Django 4.1.5 on 2023-03-18 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pharmcompany_companies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pharm_Group',
            new_name='PharmGroup',
        ),
    ]
