# Generated by Django 4.1.5 on 2023-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_revenue_revenue_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
