# Generated by Django 4.1.5 on 2023-07-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_entrancethrough_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancethrough',
            name='rate',
            field=models.FloatField(default=1),
        ),
    ]
