# Generated by Django 4.1.5 on 2023-03-18 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_pharm_group_pharmgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='existence',
            field=models.IntegerField(default=0),
        ),
    ]
