# Generated by Django 4.1.5 on 2023-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_entrancethrough_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='currency_rate',
            field=models.FloatField(default=1),
        ),
    ]
