# Generated by Django 4.1.5 on 2023-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_entrance_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancethrough',
            name='each_sell_price_afg',
            field=models.FloatField(default=0),
        ),
    ]
