# Generated by Django 4.1.5 on 2023-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_entrancethrough_each_sell_price_afg'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancethrough',
            name='rate_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
