# Generated by Django 4.1.5 on 2023-03-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_currency_store_entrance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance',
            name='medicians',
        ),
        migrations.AddField(
            model_name='entrance',
            name='medicians',
            field=models.ManyToManyField(to='core.medician'),
        ),
    ]
