# Generated by Django 4.1.5 on 2023-03-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_entrance_medicians_entrance_medicians'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
