# Generated by Django 4.1.5 on 2023-07-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_entrancethrough_rate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrancethrough',
            name='rate_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
