# Generated by Django 4.1.5 on 2023-06-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_entrance_factor_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='doctor_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medician',
            name='patient_approved',
            field=models.BooleanField(default=False),
        ),
    ]
