# Generated by Django 4.1.5 on 2023-03-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_entrance_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance',
            name='medicians',
        ),
        migrations.CreateModel(
            name='EntranceThroughModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('each_price', models.FloatField()),
                ('total', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('medician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medician')),
            ],
        ),
        migrations.AddField(
            model_name='entrance',
            name='medicians',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.entrancethroughmodel'),
            preserve_default=False,
        ),
    ]
