# Generated by Django 4.1.5 on 2023-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_entrancethrough_rate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='min_expire_date',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AlterField(
            model_name='medician',
            name='no_box',
            field=models.FloatField(default=1, null=True),
        ),
    ]
