# Generated by Django 4.1.5 on 2023-06-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_medician_doctor_approved_medician_patient_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
