# Generated by Django 4.1.5 on 2023-06-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_medician_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrancethrough',
            name='no_box',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='entrancethrough',
            name='each_quantity',
            field=models.FloatField(default=1),
        ),
    ]
