# Generated by Django 4.1.5 on 2023-03-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_entrance_medicians_entrancethroughmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrancethroughmodel',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='entrancethroughmodel',
            name='medician',
        ),
        migrations.DeleteModel(
            name='Entrance',
        ),
        migrations.DeleteModel(
            name='EntranceThroughModel',
        ),
    ]
