# Generated by Django 4.1.5 on 2023-03-25 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_entrancethroughmodel_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('price', models.IntegerField()),
                ('number', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pharmcompany')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
            ],
        ),
        migrations.CreateModel(
            name='EntranceThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('each_price', models.FloatField()),
                ('total', models.FloatField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.currency')),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.entrance')),
                ('medician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medician')),
            ],
        ),
        migrations.AddField(
            model_name='entrance',
            name='medicians',
            field=models.ManyToManyField(through='core.EntranceThrough', to='core.medician'),
        ),
        migrations.AddField(
            model_name='entrance',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store'),
        ),
    ]
