# Generated by Django 4.1.5 on 2023-08-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bigcompany_medician_big_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='medicine_1', to='core.medician')),
                ('medicine_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.medician')),
            ],
        ),
    ]
