# Generated by Django 4.1.5 on 2023-07-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_entrancethrough_no_box_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medician',
            name='batch_number',
        ),
        migrations.AddField(
            model_name='entrancethrough',
            name='batch_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
