# Generated by Django 4.1.5 on 2023-07-02 10:53

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_medician_batch_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/entrances'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(blank=True, default='', null=True, upload_to='frontend/public/dist/images/prescriptions'),
        ),
    ]
