# Generated by Django 4.1.5 on 2023-03-25 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_entrance_entrancethrough_entrance_medicians_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrance',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='entrance',
            name='number',
        ),
        migrations.RemoveField(
            model_name='entrance',
            name='price',
        ),
    ]
