# Generated by Django 4.1.5 on 2023-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_entrance_currency_remove_entrance_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrance',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
