# Generated by Django 4.1.5 on 2023-07-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_entrance_image_prescription_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
