# Generated by Django 4.1.5 on 2023-08-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_purchaselist'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselist',
            name='market_1',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
