# Generated by Django 4.1.5 on 2023-08-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_purchaselist_market_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselist',
            name='market_1',
        ),
    ]
