# Generated by Django 4.1.5 on 2023-08-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_purchaselist_market_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='shorted',
            field=models.BooleanField(default=False),
        ),
    ]
