# Generated by Django 4.1.5 on 2023-08-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_medician_shorted'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='to_buy',
            field=models.BooleanField(default=False),
        ),
    ]
