# Generated by Django 4.1.5 on 2023-07-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_revenue_revenuetrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
