# Generated by Django 4.1.5 on 2023-08-05 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_medician_to_buy'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='unsubmited_existence',
            field=models.FloatField(default=0),
        ),
    ]
