# Generated by Django 4.1.5 on 2023-08-31 11:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_medician_unsubmited_existence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='barcode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), blank=True, null=True, size=None),
        ),
    ]
