# Generated by Django 4.1.5 on 2023-08-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_medician_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
