# Generated by Django 4.1.5 on 2023-09-02 10:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_medician_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='barcode',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
