# Generated by Django 4.1.5 on 2023-09-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_medician_barcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='revenuetrough',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='revenuetrough',
            name='purchased',
            field=models.FloatField(default=0),
        ),
    ]
