# Generated by Django 4.1.5 on 2023-09-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_revenuetrough_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='refund',
            field=models.FloatField(default=0),
        ),
    ]
