# Generated by Django 4.1.5 on 2023-09-05 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_prescription_barcode_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='barcode',
            field=models.ImageField(blank=True, editable=False, upload_to='frontend/public/dist/images/prescriptions/barcodes'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='barcode_str',
            field=models.CharField(blank=True, default=0, editable=False, max_length=255),
        ),
    ]
