# Generated by Django 4.1.5 on 2023-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_prescription_timestamp_alter_prescription_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='barcode_str',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
