# Generated by Django 4.1.5 on 2023-09-29 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_city_user_alter_country_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaselistmanual',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
