# Generated by Django 4.2.5 on 2023-10-03 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_purchaselistmanual_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='start_end_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name_english',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='medician',
            name='department',
        ),
        migrations.AlterField(
            model_name='medician',
            name='maximum_existence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medician',
            name='minmum_existence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaselistmanual',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='revenuetrough',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.prescription'),
        ),
        migrations.AlterField(
            model_name='revenuetrough',
            name='revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.revenue'),
        ),
        migrations.AlterField(
            model_name='revenuetrough',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medician',
            name='department',
            field=models.ManyToManyField(blank=True, to='core.department'),
        ),
    ]
