# Generated by Django 4.1.5 on 2023-09-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_purchaselistmanual_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaselistmanual',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
