# Generated by Django 4.1.5 on 2023-10-01 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_purchaselistmanual_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='revenue',
            name='start_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='revenuetrough',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.prescription'),
        ),
        migrations.AlterField(
            model_name='revenuetrough',
            name='revenue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.revenue'),
        ),
        migrations.AlterField(
            model_name='revenuetrough',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
