# Generated by Django 4.1.5 on 2023-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_revenue_start_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medician',
            name='department',
        ),
        migrations.AlterField(
            model_name='revenue',
            name='start_end_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='medician',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, related_name='medicines', to='core.department'),
        ),
    ]
