# Generated by Django 4.1.5 on 2023-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_medician_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kind',
            name='name_english',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='medician',
            name='department',
            field=models.ManyToManyField(blank=True, to='core.department'),
        ),
    ]
