# Generated by Django 4.2.5 on 2023-10-16 17:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_medician_maximum_existence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='generic_name',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=400, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
