# Generated by Django 4.2.5 on 2023-10-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_medician_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='existence',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
