# Generated by Django 4.1.5 on 2023-01-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='cautions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dividing_rules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='generic_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='usages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
