# Generated by Django 4.1.4 on 2023-01-16 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='namee',
            new_name='name',
        ),
    ]
