# Generated by Django 4.1.4 on 2023-01-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medician', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medician',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
