# Generated by Django 4.1.4 on 2023-01-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medician', '0002_unit_medician_image_medician_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='D:/Personaly/Pharmacy App/Pharmacy_app/backend/frontend/public/images'),
        ),
    ]
