# Generated by Django 4.1.4 on 2023-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medician', '0002_medician_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='image',
            field=models.FileField(blank=True, default='', null=True, upload_to='images/'),
        ),
    ]
