# Generated by Django 4.1.4 on 2023-01-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medician', '0004_alter_medician_ml'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
