# Generated by Django 4.1.5 on 2023-03-15 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medician', '0005_alter_medician_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medician',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medician.country'),
        ),
        migrations.AlterField(
            model_name='medician',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medician.kind'),
        ),
        migrations.AlterField(
            model_name='medician',
            name='ml',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medician',
            name='no_pocket',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medician',
            name='pharm_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medician.pharm_group'),
        ),
    ]
